### ISSUE TITLE
scope hoisting should add babel-preset-env modules:false config

### ISSUE THREAD

**Issue by tjallingt** [jakoblind/webpack-configurator#1]
The module concatenation plugin only works properly when the es6 module syntax is used (so the `import Module from 'module'` syntax): https://webpack.js.org/plugins/module-concatenation-plugin/

However by default the `env` preset will transform module imports to `commonjs` style (so `var Module = require('module')`): https://github.com/babel/babel/tree/master/packages/babel-preset-env#modules

With scope hoisting enabled the babelrc should be:
```
{
  presets: [
    ['env', { modules: false }],
    'react'
  ]
}
```

Not really sure how to implement this with how the generator is currently setup.
Perhaps the React option should just default to using `babel-preset-env` in this way as it allows Webpack  to apply it tree-shaking optimisations.

**Comment by jakoblind** [comment]
I added this babel config when selecting React. Thanks for the input!
