### ISSUE TITLE
Small React Development Bugs

### ISSUE THREAD

**Issue by elliotsa** [jakoblind/webpack-configurator#19]
Hey! When running the app locally I noticed a few small React bugs:
* Feature checkbox components start uncontrolled and switched to controlled when selected, which throws an error.
* In the Features component, no key is provided when mapping over groupedFeatures and then again over featureList.

I can take care of both of those in a PR but I was curious if you had any preference on how to deal with them.

**Comment by jakoblind** [comment]
Nice! 

I haven't thought about how to fix them, so I don't have any preferences :) Awesome if you want to take a stab at this one!

**Comment by elliotsa** [comment]
No problem! Just submitted #20

**Comment by jakoblind** [comment]
Awesome!
