### ISSUE TITLE
Add vue-loader

### ISSUE THREAD

**Issue by infomaniac50** [jakoblind/webpack-configurator#4]
https://vue-loader.vuejs.org/guide/

**Comment by jakoblind** [comment]
I am on it! I have some questions as i mentioned in #5 . Do you think I should add transpliation of js files with babel-loader as default when selecting Vue, or should babel be split out to a separate option :thinking:

**Comment by infomaniac50** [comment]
When I write code in Vue files it's because I can group everything together. Most new code can be put into Vue files. If you have alot of legacy code it can be difficult to port everything. For example, you can't run Vue files through Twig templates.

https://vue-loader.vuejs.org/guide/pre-processors.html

> vue-loader allows you to use other webpack loaders to process a part of a Vue component. It will automatically infer the proper loaders to use based on the lang attribute of a language block and the rules in your webpack config.

Vue files group related code all in one place. vue-loader isn't much more than a proxy for other loaders. You can use regular ES5 javascript in the script tag of a Vue file. However browsers are becoming more ES6 aware and I use Babel.js quite often.

According to https://vue-loader.vuejs.org/spec.html#script

> Any webpack rules that match against .js files (or the extension specified by the lang attribute) will be applied to contents in the <script> block as well.

You don't have to use Babel in the script block though. You can use whatever Javascript processor you like. https://vue-loader.vuejs.org/guide/pre-processors.html#typescript I suppose you could even use coffeescript.

vue-loader is a recursive process. You can have all of the options you would with separate files and still have related code grouped together in a single file. It makes it very easy to write reusable components.

I agree with @spartanatreyu that Babel.js should be separated into a new checkbox. I have never used React but I almost always use Babel. The two things I commonly use Babel for are Classes and Module Imports.

**Comment by infomaniac50** [comment]
I created a project to see what vue-cli generates from the webpack-simple template.

This gist outlines the choices I made and the contents of webpack.config.js https://gist.github.com/infomaniac50/34255dfbfdf46476de7d0e2248b400af

https://github.com/vuejs-templates/webpack-simple
https://github.com/vuejs/vue-cli

**Comment by infomaniac50** [comment]
Also be aware that Vue Loader v15 now requires an accompanying webpack plugin to function properly.

It looks like Vue Loader v15 was released 15 days ago. New webpack configs should probably use the plugin. However the webpack-simple template is not updated yet. It does use an old version though so it should not be broken. "vue-loader": "^13.0.5"

```javascript
// webpack.config.js
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  // ...
  plugins: [
    new VueLoaderPlugin()
  ]
}
```
https://vue-loader.vuejs.org/migrating.html#a-plugin-is-now-required

**Comment by infomaniac50** [comment]
It should also be noted that vue-loader is only for Single File Components. You can have perfectly valid Vue code without SFCs. In that case, you have to load Vue from a CDN or the local server.

This is a dead simple example of a Vue app written by the author of Vue himself. http://jsfiddle.net/yyx990803/yMv7y/

**Comment by jakoblind** [comment]
Thanks for the detailed information @infomaniac50 ! 

I have created a PR: https://github.com/jakoblind/webpack-configurator/pull/12 . I would highly appreciate some testing! It seem to work fine from my perspective but this is my first time coding Vue so it would be nice if some more experienced would look at it :)

**Comment by jakoblind** [comment]
I have merged it in! :) please file a new issue if you find a bug!
